ALTER TABLE brand_pages ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE brand_pages ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE brand_page_revisions ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE brand_page_revisions ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
